from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List

from backend.core.database import get_db
from backend.models.event import Event
from backend.schemas.events import EventCreate, EventResponse
from backend.schemas.location import LocationDetails
from backend.services.weather_service import weather_service
from backend.services.recommendation_engine import RecommendationEngine
from backend.api.routes.profile import DEFAULT_USER_ID, _get_or_create_user

router = APIRouter(prefix="/events", tags=["Event Planner"])

@router.get("", response_model=List[EventResponse])
async def list_events(user_id: str = DEFAULT_USER_ID, db: Session = Depends(get_db)):
    _get_or_create_user(db, user_id)
    events = db.query(Event).filter(Event.user_id == user_id).all()
    
    # Pre-populate sample event if empty
    if not events:
        sample_ev = Event(
            user_id=user_id,
            title="College Fest & Open Air Concert",
            event_date="2026-10-18",
            event_time="18:00",
            location_name="Ahmedabad",
            latitude=23.0225,
            longitude=72.5714,
            is_outdoor="yes"
        )
        db.add(sample_ev)
        db.commit()
        events = [sample_ev]

    result = []
    for ev in events:
        loc = LocationDetails(
            name=ev.location_name,
            district=ev.location_name,
            state="Gujarat",
            country="India",
            latitude=ev.latitude,
            longitude=ev.longitude
        )
        w = await weather_service.get_weather(loc)
        comfort = RecommendationEngine.calculate_event_comfort(
            w.current.temperature, w.current.humidity, w.current.rain_probability, w.current.wind_speed
        )
        result.append(
            EventResponse(
                id=ev.id,
                title=ev.title,
                event_date=ev.event_date,
                event_time=ev.event_time,
                location_name=ev.location_name,
                latitude=ev.latitude,
                longitude=ev.longitude,
                is_outdoor=ev.is_outdoor,
                outdoor_comfort_score=comfort["score"],
                comfort_verdict=comfort["verdict"],
                advisory="Pleasant evening breeze expected. Good stability for open stages." if comfort["score"] > 70 else "Consider portable cooling or waterproof canopy.",
                forecast_temp=w.current.temperature,
                rain_risk=f"{w.current.rain_probability}% chance"
            )
        )
    return result

@router.post("", response_model=EventResponse)
async def create_event(payload: EventCreate, user_id: str = DEFAULT_USER_ID, db: Session = Depends(get_db)):
    _get_or_create_user(db, user_id)
    ev = Event(
        user_id=user_id,
        title=payload.title,
        event_date=payload.event_date,
        event_time=payload.event_time,
        location_name=payload.location_name,
        latitude=payload.latitude,
        longitude=payload.longitude,
        is_outdoor=payload.is_outdoor or "yes"
    )
    db.add(ev)
    db.commit()
    db.refresh(ev)

    loc = LocationDetails(
        name=ev.location_name,
        district=ev.location_name,
        state="India",
        latitude=ev.latitude,
        longitude=ev.longitude
    )
    w = await weather_service.get_weather(loc)
    comfort = RecommendationEngine.calculate_event_comfort(
        w.current.temperature, w.current.humidity, w.current.rain_probability, w.current.wind_speed
    )

    return EventResponse(
        id=ev.id,
        title=ev.title,
        event_date=ev.event_date,
        event_time=ev.event_time,
        location_name=ev.location_name,
        latitude=ev.latitude,
        longitude=ev.longitude,
        is_outdoor=ev.is_outdoor,
        outdoor_comfort_score=comfort["score"],
        comfort_verdict=comfort["verdict"],
        advisory="Outdoor comfort calculation generated by Mausam event scoring engine.",
        forecast_temp=w.current.temperature,
        rain_risk=f"{w.current.rain_probability}%"
    )

@router.delete("/{event_id}")
def delete_event(event_id: int, user_id: str = DEFAULT_USER_ID, db: Session = Depends(get_db)):
    ev = db.query(Event).filter(Event.id == event_id, Event.user_id == user_id).first()
    if not ev:
        raise HTTPException(status_code=404, detail="Event not found")
    db.delete(ev)
    db.commit()
    return {"status": "deleted", "id": event_id}
